# Generated by Django 4.2.9 on 2024-01-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_employe_started_alter_employe_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
