# Generated by Django 4.2.9 on 2024-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_employe_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newletter',
            old_name='contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='newletter',
            old_name='title',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='newletter',
            name='prenoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
